const inventoryData = [
  {
    id: "D074",
    product_name: "FOOTBALL",
    stock: 100,
    price: 36,
    style: "sport",
    description: "A ball used in the sport of football.",
  },
  {
    id: "A123",
    product_name: "BASKETBALL",
    stock: 50,
    price: 25,
    style: "sport",
    description: "A ball used in the sport of basketball.",
  },
  {
    id: "B456",
    product_name: "SOCCER BALL",
    stock: 75,
    price: 18,
    style: "sport",
    description: "A ball used in the sport of soccer.",
  },
  {
    id: "C789",
    product_name: "TENNIS RACKET",
    stock: 120,
    price: 50,
    style: "sport",
    description: "A racket used in the sport of tennis.",
  },
  {
    id: "E012",
    product_name: "RUNNING SHOES",
    stock: 200,
    price: 65,
    style: "sport",
    description: "Shoes designed for running.",
  },
  {
    id: "F345",
    product_name: "GOLF CLUB",
    stock: 90,
    price: 75,
    style: "sport",
    description: "A club used in the sport of golf.",
  },
  {
    id: "G678",
    product_name: "SWIMMING GOGGLES",
    stock: 30,
    price: 12,
    style: "sport",
    description: "Goggles used in the sport of swimming.",
  },
  {
    id: "H901",
    product_name: "BASEBALL GLOVE",
    stock: 150,
    price: 40,
    style: "sport",
    description: "A glove used in the sport of baseball.",
  },
  {
    id: "I234",
    product_name: "HIKING BOOTS",
    stock: 80,
    price: 55,
    style: "sport",
    description: "Boots designed for hiking.",
  },
  {
    id: "J567",
    product_name: "CYCLING HELMET",
    stock: 110,
    price: 30,
    style: "sport",
    description: "A helmet used in the sport of cycling.",
  },
  {
    id: "K890",
    product_name: "VOLLEYBALL",
    stock: 60,
    price: 28,
    style: "sport",
    description: "A ball used in the sport of volleyball.",
  },
  {
    id: "L123",
    product_name: "SKI POLES",
    stock: 85,
    price: 42,
    style: "sport",
    description: "Poles used in the sport of skiing.",
  },
  {
    id: "M456",
    product_name: "ROLLERBLADES",
    stock: 95,
    price: 60,
    style: "sport",
    description: "Rollerblades for inline skating.",
  },
  {
    id: "N789",
    product_name: "YOGA MAT",
    stock: 130,
    price: 20,
    style: "sport",
    description: "A mat used in the practice of yoga.",
  },
  {
    id: "O012",
    product_name: "PING PONG PADDLE",
    stock: 180,
    price: 15,
    style: "sport",
    description: "A paddle used in the sport of ping pong.",
  },
  {
    id: "P345",
    product_name: "WEIGHT LIFTING GLOVES",
    stock: 70,
    price: 35,
    style: "sport",
    description: "Gloves used in weight lifting.",
  },
  {
    id: "Q678",
    product_name: "JUMP ROPE",
    stock: 40,
    price: 10,
    style: "sport",
    description: "A rope used in the activity of jumping rope.",
  },
  {
    id: "R901",
    product_name: "SURFBOARD",
    stock: 120,
    price: 80,
    style: "sport",
    description: "A board used in the sport of surfing.",
  },
  {
    id: "S234",
    product_name: "CLIMBING HARNESS",
    stock: 55,
    price: 50,
    style: "sport",
    description: "A harness used in the activity of climbing.",
  },
  {
    id: "T567",
    product_name: "FOOTBALL HELMET",
    stock: 105,
    price: 45,
    style: "sport",
    description: "A helmet used in the sport of football.",
  },
];

export default inventoryData;
