const inventoryData = [
  {
    id: 1,
    product_name: "FOOTBALL",
    stock: 100,
    price: 36,
    type: "sport",
    description: "A ball used in the sport of football.",
  },
  {
    id: 2,
    product_name: "BASKETBALL",
    stock: 50,
    price: 25,
    type: "sport",
    description: "A ball used in the sport of basketball.",
  },
  {
    id: 3,
    product_name: "SOCCER BALL",
    stock: 75,
    price: 18,
    type: "sport",
    description: "A ball used in the sport of soccer.",
  },
  {
    id: 4,
    product_name: "TENNIS RACKET",
    stock: 120,
    price: 50,
    type: "sport",
    description: "A racket used in the sport of tennis.",
  },
  {
    id: 5,
    product_name: "RUNNING SHOES",
    stock: 200,
    price: 65,
    type: "sport",
    description: "Shoes designed for running.",
  },
  {
    id: 6,
    product_name: "GOLF CLUB",
    stock: 90,
    price: 75,
    type: "sport",
    description: "A club used in the sport of golf.",
  },
  {
    id: 7,
    product_name: "SWIMMING GOGGLES",
    stock: 30,
    price: 12,
    type: "sport",
    description: "Goggles used in the sport of swimming.",
  },
  {
    id: 8,
    product_name: "BASEBALL GLOVE",
    stock: 150,
    price: 40,
    type: "sport",
    description: "A glove used in the sport of baseball.",
  },
  {
    id: 9,
    product_name: "HIKING BOOTS",
    stock: 80,
    price: 55,
    type: "sport",
    description: "Boots designed for hiking.",
  },
  {
    id: 10,
    product_name: "CYCLING HELMET",
    stock: 110,
    price: 30,
    type: "sport",
    description: "A helmet used in the sport of cycling.",
  },
  {
    id: 11,
    product_name: "VOLLEYBALL",
    stock: 60,
    price: 28,
    type: "sport",
    description: "A ball used in the sport of volleyball.",
  },
  {
    id: 12,
    product_name: "SKI POLES",
    stock: 85,
    price: 42,
    type: "sport",
    description: "Poles used in the sport of skiing.",
  },
  {
    id: 13,
    product_name: "ROLLERBLADES",
    stock: 95,
    price: 60,
    type: "sport",
    description: "Rollerblades for inline skating.",
  },
  {
    id: 14,
    product_name: "YOGA MAT",
    stock: 130,
    price: 20,
    type: "sport",
    description: "A mat used in the practice of yoga.",
  },
  {
    id: 15,
    product_name: "PING PONG PADDLE",
    stock: 180,
    price: 15,
    type: "sport",
    description: "A paddle used in the sport of ping pong.",
  },
  {
    id: 16,
    product_name: "WEIGHT LIFTING GLOVES",
    stock: 70,
    price: 35,
    type: "sport",
    description: "Gloves used in weight lifting.",
  },
  {
    id: 17,
    product_name: "JUMP ROPE",
    stock: 40,
    price: 10,
    type: "sport",
    description: "A rope used in the activity of jumping rope.",
  },
  {
    id: 18,
    product_name: "SURFBOARD",
    stock: 120,
    price: 80,
    type: "sport",
    description: "A board used in the sport of surfing.",
  },
  {
    id: 19,
    product_name: "CLIMBING HARNESS",
    stock: 55,
    price: 50,
    type: "sport",
    description: "A harness used in the activity of climbing.",
  },
  {
    id: 20,
    product_name: "FOOTBALL HELMET",
    stock: 105,
    price: 45,
    type: "sport",
    description: "A helmet used in the sport of football.",
  },
];

export default inventoryData;
